version: "3.5"

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
      - ./database/data:/var/lib/postgresql/data
    networks:
      - app.network

networks:
  app.network:
    driver: bridge

volumes:
  postgres.data: