server:
  servlet:
    context-path: /picpay

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    org.springframework.web: ${LOG_LEVEL:INFO}
    org.hibernate: ${LOG_LEVEL:INFO}
    com.picpay: ${LOG_LEVEL:DEBUG}

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=picpay}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      poolName: SpringBootJPAHikariCP
      minimumIdle: 20
      maximumPoolSize: 200
      connectionTimeout: 30000
      idleTimeout: 30000
      maxLifetime: 2000000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        hibernate:
          default_schema: picpay

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 5000
          multiplier: 1
          max-interval: 300000

  mail:
    host: smtp.sendgrid.net
    port: 587
    username: apikey
    password: ${SENDGRID_API_KEY}

autorizador:
  api:
    server: https://run.mocky.io/v3/5794d450-d2e2-4412-8131-73d0293ac1cc

picpay:
  email:
    remetente: PicPay <naoresponderbeneficios@outlook.com.br>

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path: /public/swagger
